---
- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: create directory
  file:
    path: /home/ubuntu/prometheus
    state: directory

- name: download prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-amd64.tar.gz"
    dest: "/home/ubuntu/prometheus/prometheus-2.47.2.linux-amd64.tar.gz"

- name: unpack installation files
  unarchive:
    src: "/home/ubuntu/prometheus/prometheus-2.47.2.linux-amd64.tar.gz"
    dest: "/home/ubuntu/prometheus"
    remote_src: yes

- name: move files
  copy:
    src: "/home/ubuntu/prometheus/prometheus-2.47.2.linux-amd64/"
    dest: "/usr/local/bin/prometheus/"
    remote_src: yes

- name: copy config file
  ansible.builtin.copy:
    src: files/prometheus.yml
    dest: "/usr/local/bin/prometheus/prometheus.yml"

- name: copy rules file
  ansible.builtin.copy:
    src: files/first_rules.yml
    dest: "/usr/local/bin/prometheus/first_rules.yml"

- name: copy rules file
  ansible.builtin.copy:
    src: files/second_rules.yml
    dest: "/usr/local/bin/prometheus/second_rules.yml"

- name: copy env file
  ansible.builtin.copy:
    src: files/alertmanager.env
    dest: "/usr/local/bin/alertmanager/alertmanager.env"

- name: copy alertmanager file
  ansible.builtin.copy:
    src: files/alertmanager.yml
    dest: "/usr/local/bin/alertmanager/alertmanager.yml"

- name: create service file
  copy:
    dest: "/etc/systemd/system/prometheus.service"
    content: |
      [Unit]
      Description=Prometheus Service
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/prometheus/prometheus --config.file=/usr/local/bin/prometheus/prometheus.yml
      EnvironmentFile=/usr/local/bin/alertmanager/alertmanager.env

      [Install]
      WantedBy=multi-user.target

- name: service always restarted
  systemd:
    name: prometheus
    state: restarted
    enabled: true
    daemon_reload: yes